package edu.tamu.scholars.middleware.graphql.model.concept;

import static com.fasterxml.jackson.annotation.JsonInclude.Include.NON_EMPTY;

import com.fasterxml.jackson.annotation.JsonInclude;
import edu.tamu.scholars.middleware.graphql.model.AbstractNestedDocument;
import io.leangen.graphql.annotations.types.GraphQLType;
import java.lang.String;

/**
 * This file is automatically generated on compile.
 *
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */
@GraphQLType(
    name = "ConceptReceipt"
)
@JsonInclude(NON_EMPTY)
public class Receipt extends AbstractNestedDocument {
  private static final long serialVersionUID = -1142246644L;

  private String recipientName;

  public Receipt() {
    super();
  }

  public String getRecipientName() {
    return recipientName;
  }

  public void setRecipientName(String recipientName) {
    this.recipientName = recipientName;
  }
}
