PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX tamu: <http://vivo.library.tamu.edu/ontology/TAMU#>
 
CONSTRUCT {
    ?grant tamu:awardedBy_label ?labelWithId .
} WHERE {
    <{{uri}}> obo:RO_0000053 ?role .
    ?role a vivo:ResearcherRole .
    ?role vivo:relatedBy ?grant .
    ?grant vivo:assignedBy ?awardedBy .
    ?grant tamu:awardedBy_label ?label .
    BIND( CONCAT( STR(?label), REPLACE(STR(?grant), "(^.*/)", "::"), REPLACE(STR(?awardedBy), "(^.*/)", "::") ) AS ?labelWithId ) .
}
