PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

CONSTRUCT {
    ?publication obo:ARG_0000015 ?tagWithId .
} WHERE {
    <{{uri}}> vivo:relatedBy ?authorship .
    ?authorship a vivo:Authorship .
    ?authorship vivo:relates ?publication .
    ?publication a obo:IAO_0000030 .
    ?publication obo:ARG_0000015 ?tag .
    BIND( CONCAT( STR(?tag), REPLACE(STR(?publication), "(^.*/)", "::") ) AS ?tagWithId ) .
}
