language: java

jdk:
  - openjdk8
  - openjdk10
  - openjdk11

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - mvn clean test jacoco:report coveralls:report

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: false
  target-branch: gh-pages
  github_token: "$GITHUB_TOKEN"
  local_dir: "./target/generated-docs"
  on:
    branch: master
