# final base image
FROM openjdk:8u171-jre-alpine

# set deployment directory
WORKDIR /scholars

# copy over the built artifact from the maven image
COPY /target/middleware*.jar ./scholars-discovery.jar

# set the startup command to run your binary
CMD ["java", "-jar", "./scholars-discovery.jar"]
