package edu.tamu.scholars.middleware.graphql.model.relationship;

import static com.fasterxml.jackson.annotation.JsonInclude.Include.NON_EMPTY;

import com.fasterxml.jackson.annotation.JsonInclude;
import edu.tamu.scholars.middleware.graphql.model.AbstractNestedDocument;
import io.leangen.graphql.annotations.types.GraphQLType;

/**
 * This file is automatically generated on compile.
 *
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */
@GraphQLType(
    name = "RelationshipPrincipalInvestigator"
)
@JsonInclude(NON_EMPTY)
public class PrincipalInvestigator extends AbstractNestedDocument {
  private static final long serialVersionUID = -2132647193L;

  public PrincipalInvestigator() {
    super();
  }
}
