PREFIX tamu: <http://vivo.library.tamu.edu/ontology/TAMU#>

CONSTRUCT {
    <{{uri}}> tamu:publishedProceedings ?publishedProceedings .
} WHERE {
    <{{uri}}> tamu:publishedProceedings ?publishedProceedings .
}
