package edu.tamu.scholars.middleware.graphql.model.person;

import static com.fasterxml.jackson.annotation.JsonInclude.Include.NON_EMPTY;

import com.fasterxml.jackson.annotation.JsonInclude;
import edu.tamu.scholars.middleware.graphql.model.AbstractNestedDocument;
import io.leangen.graphql.annotations.types.GraphQLType;
import java.lang.String;

/**
 * This file is automatically generated on compile.
 *
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */
@GraphQLType(
    name = "PersonEditorOf"
)
@JsonInclude(NON_EMPTY)
public class EditorOf extends AbstractNestedDocument {
  private static final long serialVersionUID = 560215351L;

  private String type;

  private String publisher;

  private String authors;

  private String pageStart;

  private String pageEnd;

  private String date;

  public EditorOf() {
    super();
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getPublisher() {
    return publisher;
  }

  public void setPublisher(String publisher) {
    this.publisher = publisher;
  }

  public String getAuthors() {
    return authors;
  }

  public void setAuthors(String authors) {
    this.authors = authors;
  }

  public String getPageStart() {
    return pageStart;
  }

  public void setPageStart(String pageStart) {
    this.pageStart = pageStart;
  }

  public String getPageEnd() {
    return pageEnd;
  }

  public void setPageEnd(String pageEnd) {
    this.pageEnd = pageEnd;
  }

  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }
}
