package edu.tamu.scholars.middleware.graphql.model.person;

import static com.fasterxml.jackson.annotation.JsonInclude.Include.NON_EMPTY;

import com.fasterxml.jackson.annotation.JsonInclude;
import edu.tamu.scholars.middleware.graphql.model.AbstractNestedDocument;
import io.leangen.graphql.annotations.types.GraphQLType;

/**
 * This file is automatically generated on compile.
 *
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */
@GraphQLType(
    name = "PersonPositionOrganizationParent"
)
@JsonInclude(NON_EMPTY)
public class PositionOrganizationParent extends AbstractNestedDocument {
  private static final long serialVersionUID = -1355915495L;

  public PositionOrganizationParent() {
    super();
  }
}
