package edu.tamu.scholars.middleware.graphql.model.person;

import edu.tamu.scholars.middleware.graphql.model.person.ResearcherOnAwardedBy;

import static com.fasterxml.jackson.annotation.JsonInclude.Include.NON_EMPTY;

import com.fasterxml.jackson.annotation.JsonInclude;
import edu.tamu.scholars.middleware.graphql.model.AbstractNestedDocument;
import io.leangen.graphql.annotations.types.GraphQLType;
import java.lang.String;

/**
 * This file is automatically generated on compile.
 *
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */
@GraphQLType(
    name = "PersonResearcherOn"
)
@JsonInclude(NON_EMPTY)
public class ResearcherOn extends AbstractNestedDocument {
  private static final long serialVersionUID = 86706970L;

  private String label;

  private ResearcherOnAwardedBy awardedBy;

  private String role;

  private String startDate;

  private String endDate;

  public ResearcherOn() {
    super();
  }

  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public ResearcherOnAwardedBy getAwardedBy() {
    return awardedBy;
  }

  public void setAwardedBy(ResearcherOnAwardedBy awardedBy) {
    this.awardedBy = awardedBy;
  }

  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }

  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }
}
