package edu.tamu.scholars.middleware.graphql.model;

import edu.tamu.scholars.middleware.discovery.model.AbstractIndexDocument;
import io.leangen.graphql.annotations.types.GraphQLInterface;
import java.io.Serializable;

/**
 * This file is automatically generated on compile.
 *
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */
@GraphQLInterface(
    name = "AbstractNestedDocument",
    implementationAutoDiscovery = true
)
public abstract class AbstractNestedDocument extends AbstractIndexDocument implements Serializable {
  private static final long serialVersionUID = -849883046L;

  public AbstractNestedDocument() {
    super();
  }
}
