package edu.tamu.scholars.middleware.graphql.model;

import edu.tamu.scholars.middleware.graphql.model.process.OfferedBy;
import edu.tamu.scholars.middleware.graphql.model.process.OccursWithinEvent;
import edu.tamu.scholars.middleware.graphql.model.process.IncludesEvent;
import edu.tamu.scholars.middleware.graphql.model.process.InEventSery;
import edu.tamu.scholars.middleware.graphql.model.process.Participant;
import edu.tamu.scholars.middleware.graphql.model.process.SubjectArea;
import edu.tamu.scholars.middleware.graphql.model.process.HasPrerequisite;
import edu.tamu.scholars.middleware.graphql.model.process.PrerequisiteFor;
import edu.tamu.scholars.middleware.graphql.model.process.GeographicFocus;
import edu.tamu.scholars.middleware.graphql.model.process.OutputPublicationOrOtherWork;
import edu.tamu.scholars.middleware.graphql.model.process.RelatedDocument;
import edu.tamu.scholars.middleware.graphql.model.process.HeldInFacility;
import edu.tamu.scholars.middleware.graphql.model.process.HeldInGeographicLocation;
import edu.tamu.scholars.middleware.graphql.model.process.HasOutput;
import edu.tamu.scholars.middleware.graphql.model.process.HasParticipant;
import edu.tamu.scholars.middleware.graphql.model.common.Website;
import edu.tamu.scholars.middleware.graphql.model.common.SameAs;

import static com.fasterxml.jackson.annotation.JsonInclude.Include.NON_EMPTY;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.leangen.graphql.annotations.types.GraphQLType;
import java.lang.String;
import java.util.List;

/**
 * This file is automatically generated on compile.
 *
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */
@GraphQLType(
    name = "Process"
)
@JsonInclude(NON_EMPTY)
public class Process extends AbstractNestedDocument {
  private static final long serialVersionUID = 262133449L;

  private List<OfferedBy> offeredBy;

  private List<OccursWithinEvent> occursWithinEvent;

  private List<IncludesEvent> includesEvent;

  private List<InEventSery> inEventSeries;

  private List<Participant> participants;

  private List<SubjectArea> subjectAreas;

  private List<HasPrerequisite> hasPrerequisite;

  private List<PrerequisiteFor> prerequisiteFor;

  private List<GeographicFocus> geographicFocus;

  private List<OutputPublicationOrOtherWork> outputPublicationOrOtherWork;

  private List<RelatedDocument> relatedDocuments;

  private List<HeldInFacility> heldInFacility;

  private List<HeldInGeographicLocation> heldInGeographicLocation;

  private List<HasOutput> hasOutput;

  private List<HasParticipant> hasParticipant;

  private List<Website> websites;

  private List<SameAs> sameAs;

  private String title;

  private String description;

  private String dateTimeIntervalStart;

  private String dateTimeIntervalEnd;

  private String credits;

  private String contactInformation;

  private List<String> type;

  private String image;

  private String thumbnail;

  private String modTime;

  @JsonProperty("class")
  private String clazz;

  public Process() {
    super();
  }

  public List<OfferedBy> getOfferedBy() {
    return offeredBy;
  }

  public void setOfferedBy(List<OfferedBy> offeredBy) {
    this.offeredBy = offeredBy;
  }

  public List<OccursWithinEvent> getOccursWithinEvent() {
    return occursWithinEvent;
  }

  public void setOccursWithinEvent(List<OccursWithinEvent> occursWithinEvent) {
    this.occursWithinEvent = occursWithinEvent;
  }

  public List<IncludesEvent> getIncludesEvent() {
    return includesEvent;
  }

  public void setIncludesEvent(List<IncludesEvent> includesEvent) {
    this.includesEvent = includesEvent;
  }

  public List<InEventSery> getInEventSeries() {
    return inEventSeries;
  }

  public void setInEventSeries(List<InEventSery> inEventSeries) {
    this.inEventSeries = inEventSeries;
  }

  public List<Participant> getParticipants() {
    return participants;
  }

  public void setParticipants(List<Participant> participants) {
    this.participants = participants;
  }

  public List<SubjectArea> getSubjectAreas() {
    return subjectAreas;
  }

  public void setSubjectAreas(List<SubjectArea> subjectAreas) {
    this.subjectAreas = subjectAreas;
  }

  public List<HasPrerequisite> getHasPrerequisite() {
    return hasPrerequisite;
  }

  public void setHasPrerequisite(List<HasPrerequisite> hasPrerequisite) {
    this.hasPrerequisite = hasPrerequisite;
  }

  public List<PrerequisiteFor> getPrerequisiteFor() {
    return prerequisiteFor;
  }

  public void setPrerequisiteFor(List<PrerequisiteFor> prerequisiteFor) {
    this.prerequisiteFor = prerequisiteFor;
  }

  public List<GeographicFocus> getGeographicFocus() {
    return geographicFocus;
  }

  public void setGeographicFocus(List<GeographicFocus> geographicFocus) {
    this.geographicFocus = geographicFocus;
  }

  public List<OutputPublicationOrOtherWork> getOutputPublicationOrOtherWork() {
    return outputPublicationOrOtherWork;
  }

  public void setOutputPublicationOrOtherWork(
      List<OutputPublicationOrOtherWork> outputPublicationOrOtherWork) {
    this.outputPublicationOrOtherWork = outputPublicationOrOtherWork;
  }

  public List<RelatedDocument> getRelatedDocuments() {
    return relatedDocuments;
  }

  public void setRelatedDocuments(List<RelatedDocument> relatedDocuments) {
    this.relatedDocuments = relatedDocuments;
  }

  public List<HeldInFacility> getHeldInFacility() {
    return heldInFacility;
  }

  public void setHeldInFacility(List<HeldInFacility> heldInFacility) {
    this.heldInFacility = heldInFacility;
  }

  public List<HeldInGeographicLocation> getHeldInGeographicLocation() {
    return heldInGeographicLocation;
  }

  public void setHeldInGeographicLocation(List<HeldInGeographicLocation> heldInGeographicLocation) {
    this.heldInGeographicLocation = heldInGeographicLocation;
  }

  public List<HasOutput> getHasOutput() {
    return hasOutput;
  }

  public void setHasOutput(List<HasOutput> hasOutput) {
    this.hasOutput = hasOutput;
  }

  public List<HasParticipant> getHasParticipant() {
    return hasParticipant;
  }

  public void setHasParticipant(List<HasParticipant> hasParticipant) {
    this.hasParticipant = hasParticipant;
  }

  public List<Website> getWebsites() {
    return websites;
  }

  public void setWebsites(List<Website> websites) {
    this.websites = websites;
  }

  public List<SameAs> getSameAs() {
    return sameAs;
  }

  public void setSameAs(List<SameAs> sameAs) {
    this.sameAs = sameAs;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getDateTimeIntervalStart() {
    return dateTimeIntervalStart;
  }

  public void setDateTimeIntervalStart(String dateTimeIntervalStart) {
    this.dateTimeIntervalStart = dateTimeIntervalStart;
  }

  public String getDateTimeIntervalEnd() {
    return dateTimeIntervalEnd;
  }

  public void setDateTimeIntervalEnd(String dateTimeIntervalEnd) {
    this.dateTimeIntervalEnd = dateTimeIntervalEnd;
  }

  public String getCredits() {
    return credits;
  }

  public void setCredits(String credits) {
    this.credits = credits;
  }

  public String getContactInformation() {
    return contactInformation;
  }

  public void setContactInformation(String contactInformation) {
    this.contactInformation = contactInformation;
  }

  public List<String> getType() {
    return type;
  }

  public void setType(List<String> type) {
    this.type = type;
  }

  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public String getThumbnail() {
    return thumbnail;
  }

  public void setThumbnail(String thumbnail) {
    this.thumbnail = thumbnail;
  }

  public String getModTime() {
    return modTime;
  }

  public void setModTime(String modTime) {
    this.modTime = modTime;
  }

  public String getClazz() {
    return clazz;
  }

  public void setClazz(String clazz) {
    this.clazz = clazz;
  }
}
