PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
    ?person vivo:hrJobTitle ?titleWithId .
} WHERE {
    {
        <[(${uri})]> vivo:relatedBy ?position .
        ?position a vivo:Position .
        ?position vivo:relatedBy ?person .
        ?person a foaf:Person .
        ?person vivo:hrJobTitle ?title .
        BIND( CONCAT( STR(?title), REPLACE(STR(?person), "(^.*/)", "::") ) AS ?titleWithId ) .
    }
    UNION
    {
        <[(${uri})]> obo:BFO_0000051 ?organization .
        ?organization vivo:relatedBy ?position .
        ?position a vivo:Position .
        ?position vivo:relatedBy ?person .
        ?person a foaf:Person .
        ?person vivo:hrJobTitle ?title .
        BIND( CONCAT( STR(?title), REPLACE(STR(?person), "(^.*/)", "::") ) AS ?titleWithId ) .
    }
}