PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?dateTimeInterval vivo:dateTimePrecision ?dateTimePrecision .
} WHERE {
    <{{uri}}> vivo:dateTimeInterval ?dateTimeInterval .
    ?dateTimeInterval vivo:dateTimePrecision ?dateTimePrecision .
}
