PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    <{{uri}}> vivo:dateTimeInterval ?dateTimeIntervalWithId .
} WHERE {
    <{{uri}}> vivo:dateTimeInterval ?dateTimeInterval .
    BIND(CONCAT(STR(?dateTimeInterval), REPLACE(STR(?dateTimeInterval), "(^.*/)", "::") ) AS ?dateTimeIntervalWithId) .
}
