PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?endDate vivo:dateTimePrecision ?dateTimePrecisionWithId .
} WHERE {
    <{{uri}}> vivo:dateTimeInterval ?dateTimeInterval .
    ?dateTimeInterval vivo:end ?endDate .
    ?endDate vivo:dateTimePrecision ?dateTimePrecision .
    BIND( CONCAT( CONCAT( STR(?dateTimePrecision), REPLACE(STR(?dateTimeInterval), "(^.*/)", "::"), REPLACE(STR(?endDate), "(^.*/)", "::") ) ) AS ?dateTimePrecisionWithId) .
}
