PREFIX tamu: <http://vivo.library.tamu.edu/ontology/TAMU#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    <{{uri}}> tamu:awardedBy_label ?labelWithId .
} WHERE {
    <{{uri}}> tamu:awardedBy_label ?label .
    <{{uri}}> vivo:assignedBy ?assignedBy ; a vivo:Grant .
    BIND( CONCAT( STR(?label), REPLACE(STR(?assignedBy), "(^.*/)", "::") ) AS ?labelWithId ) .
}
