FROM solr:7.7.2-slim

RUN precreate-core persons
RUN precreate-core organizations
RUN precreate-core documents
RUN precreate-core relationships
RUN precreate-core processes
RUN precreate-core collections
RUN precreate-core concepts

COPY ./config /opt/solr/server/solr/mycores/persons
COPY ./config /opt/solr/server/solr/mycores/organizations
COPY ./config /opt/solr/server/solr/mycores/documents
COPY ./config /opt/solr/server/solr/mycores/relationships
COPY ./config /opt/solr/server/solr/mycores/processes
COPY ./config /opt/solr/server/solr/mycores/collections
COPY ./config /opt/solr/server/solr/mycores/concepts

RUN chmod -R g=u /opt/solr/server/solr
RUN chmod -R ugo+w /opt/solr/server/solr/
RUN chmod -R ugo+w /opt/solr/server/logs/

