PREFIX tamu: <http://vivo.library.tamu.edu/ontology/TAMU#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?relationship tamu:awardConferredBy_label ?label .
} WHERE {
    <{{uri}}> vivo:relatedBy ?relationship ; a vivo:Award .
    ?relationship tamu:awardConferredBy_label ?label .
}
